# Generated by Django 3.2.6 on 2021-08-27 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='object',
        ),
        migrations.RemoveField(
            model_name='post',
            name='test',
        ),
        migrations.AddField(
            model_name='object',
            name='post_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.post'),
        ),
    ]
