# Generated by Django 3.2.6 on 2021-08-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('discription', models.TextField(blank=True, verbose_name='概要')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='object',
            field=models.ManyToManyField(to='articles.Object'),
        ),
    ]
