openapi: 3.0.3
info:
  title: Ochiba API Reference
  version: 1.0.0
  description: Your project description
paths:
  /api/articles/:
    get:
      operationId: articles_retrieve
      tags:
      - articles
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
